from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('world_cups/', views.worldcups_index, name='index'),
    path('world_cups/<int:cup_id>', views.worldcups_details, name='detail'),
    path('world_cups/create/',
         views.CupCreate.as_view(),
         name='world_cups_create'),
    path('world_cups/<int:pk>/update/',
         views.CupUpdate.as_view(),
         name='world_cups_update'),
    path('world_cups/<int:pk>/delete/',
         views.CupDelete.as_view(),
         name='world_cups_delete'),
    path('world_cups/<int:cup_id>/add_fan/', views.add_fan, name='add_fan'),
    path("world_cups/<int:cup_id>/assoc_attire/<int:item_id>/",
         views.assoc_attire,
         name="assoc_attire"),
    path("world_cups/<int:cup_id>/add_photo/",
         views.add_photo,
         name="add_photo"),
    path('items/', views.items_index, name='all_items'),
    path('items/<int:item_id>/', views.item_detail, name='item_detail'),
    path('items/create/', views.Create_item.as_view(), name='create_item'),
    path("items/<int:pk>/update/",
         views.Update_item.as_view(),
         name="update_item"),
    path("items/<int:pk>/delete/",
         views.Delete_item.as_view(),
         name="delete_item"),
]