# Generated by Django 3.2 on 2021-04-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World_Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('champion', models.CharField(max_length=40)),
                ('runner_up', models.CharField(max_length=40)),
                ('mvps', models.TextField(max_length=255)),
                ('champion_score', models.IntegerField()),
                ('runner_up_score', models.IntegerField()),
            ],
        ),
    ]
