# Generated by Django 3.2 on 2021-04-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_fan'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanAttire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing', models.CharField(choices=[('H', 'Hat'), ('S', 'Shirt'), ('P', 'Pants'), ('N', 'None')], default='N', max_length=5)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='fan',
            name='country_of_residency',
            field=models.CharField(max_length=20, verbose_name='Country/Planet of Residence'),
        ),
        migrations.AddField(
            model_name='fan',
            name='fan_attire',
            field=models.ManyToManyField(to='main_app.FanAttire'),
        ),
    ]
