# Generated by Django 3.2 on 2021-04-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210421_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanattire',
            name='clothing',
            field=models.CharField(choices=[('Hat', 'Hat'), ('Shirt', 'Shirt'), ('Pants', 'Pants'), ('None', 'None')], default='None', max_length=5),
        ),
    ]
