# Generated by Django 3.2 on 2021-04-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_fanattire_clothing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fan',
            name='fan_attire',
        ),
        migrations.AddField(
            model_name='world_cup',
            name='fan_attire',
            field=models.ManyToManyField(to='main_app.FanAttire'),
        ),
    ]
