# Generated by Django 3.2 on 2021-04-22 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210421_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('world_cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.world_cup')),
            ],
        ),
    ]
